### ISSUE TITLE
app does not work offline [airplane] with cached content

### ISSUE THREAD

**Issue by brianPlummer** [digitalbuddha/StoreDemo#10]
we are missing an onError and graceful fail here

 Process: com.nytimes.storedemo, PID: 8634
                                                 java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: rx.exceptions.OnErrorNotImplementedException: Failed to connect to reddit.com/198.41.209.143:80

**Comment by digitalbuddha** [comment]
I'm assuming something is wrong with cache control. Will look today.
